config/routes.rb
Rails.application.routes.draw do
  root 'user#login'
  
  get 'signup', to: 'user#new'
  post 'signup', to: 'user#create'

  get 'login', to: 'user#login'
  post 'login', to: 'user#login_attempt'
  
  get 'logout', to: 'user#logout'

  get 'player', to: 'player#home'
  get 'master', to: 'master#home'

  get 'newchar', to: 'character#new'
  post 'newchar', to: 'character#create'

  post 'rmchar', to: 'character#remove' 
  
  get 'character/:id', to: 'character#show', as: 'character'

  get 'setstat', to: 'stats#new'
  post 'setstat', to: 'stats#create'

  get 'skills', to: "skill#entrypoint"

  get 'agelimits', to: "stats#age_limits"
  post 'agelimits', to: "stats#new_points"
end

app/models/character.rb
class Character < ApplicationRecord
    def self.ocupations 
        [
            "Advogado",
            "Andarilho",
            "Antiquário",
            "Artista",
            "Atleta",
            "Autor",
            "Bibliotecário",
            "Membro do clero",
            "Criminoso",
            "Detetive particular",
            "Diletante",
            "Engenheiro",
            "Fanático",
            "Fazendeiro",
            "Hacker",
            "Investigador de polícia",
            "Jornalista",
            "Médico",
            "Membro de tribo",
            "Missionário",
            "Músico",
            "Oficial de polícia",
            "Oficial militar",
            "Parapsicólogo",
            "Piloto",
            "Professor",
            "Profissional do entretenimento",
            "Soldado"
        ]
    end

    belongs_to :user
    has_one :stat, dependent: :destroy
    has_one :current_stat, dependent: :destroy

    validates :name, :presence => true, :length => { :in => 3..50 }
    validates :ocupation, :presence => true, numericality: { only_integer: true, less_than: 28, greater_than: -1 }
    validates :birth_place, :presence => true
    validates :age, :presence => true, numericality: { only_integer: true, greater_than: 17, less_than: 90}
    validates :sex, :presence => true
    

end

app/controllers/character_controller.rb
class CharacterController < ApplicationController
	before_action :authenticate_user
	before_action :validate_char, :only => [:remove]

	def new
		@char = Character.new
	end

	def show
		session[:character_id] = params[:id]
		if not validate_char()
			redirect_to :controller => 'player', :action => 'home'
		elsif not stats_set()
			redirect_to :controller => 'stats', :action => 'new'
		elsif not stats_done()
			redirect_to :controller => 'stats', :action => 'age_limits'
		end
	end

	def edit
	end

	def list
	end

	def remove
		if @char.destroy
			redirect_to :controller => 'player', :action => 'home'
		else
			redirect_to @char
		end 
	end

	def create
		@char = Character.new(create_char_params.merge(:user_id => @current_user.id))
		if @char.save
			session[:character_id] = @char.id
			redirect_to :controller => 'stats', :action => 'new'
		else
			render 'new'
		end
	end

	private 
	def create_char_params
		params.require(:character).permit(:name, :ocupation, :birth_place, :mental_illnesses, :age, :sex)
	end


end

app/helpers/character_helper.rb
module CharacterHelper
end

app/views/character/create.html.erb
<h1>Character#create</h1>
<p>Find me in app/views/character/create.html.erb</p>

app/views/character/edit.html.erb
<h1>Character#edit</h1>
<p>Find me in app/views/character/edit.html.erb</p>

app/views/character/list.html.erb
<h1>Character#list</h1>
<p>Find me in app/views/character/list.html.erb</p>

app/views/character/new.html.erb
<div class='newchar'>
    <%= form_with scope: :character, url: newchar_path, local: true do |f|%>
        <div class="form-group wrapper-newchar" id='newchar-name'>
            <h1 style='grid-area: 2 / 3 / 2 / 6; text-align: center'>Escolha o nome do seu personagem</h1>
            <%= f.text_field :name, :class => 'form-control align-self-center', :autocomplete =>'off', :required => 'true', :pattern => '.{3,}', :style => 'grid-area: 3 / 3 / 3 / 6'%>
            <a class='btn btn-primary align-self-center' onclick="fase2()" id='fase-2' style='grid-area: 4 / 4 / 4 / 5'>Continuar</a>

            <% if @char.errors.any? %>
                <div class="toast errors-toast" style="grid-area: 1/6/3/8; " role="alert" aria-live="assertive" data-autohide="false" aria-atomic="true">
                    <div class="toast-header">
                        <strong class="mr-auto">Erros</strong>
                        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="toast-body">
                        <% for message_error in @char.errors.full_messages %>
                        <p><%= message_error %></p>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="form-group wrapper-newchar " id='newchar-ocupation'>
            <h1 style='grid-area: 2 / 3 / 2 / 6; text-align: center'>Escolha uma ocupação</h1>
            <%= f.select :ocupation, Character.ocupations.each_with_index.map { |c,i| [c, i] }, {}, { :class => 'form-control align-self-center', :style => 'grid-area: 3 / 3 / 3 / 6' } %>
            <a class='btn btn-primary align-self-center' id='fase-3' style='grid-area: 4 / 4 / 4 / 5'>Continuar</a>
        </div>
        <div class="form-group wrapper-newchar" id='newchar-bp'>
            <h1 style='grid-area: 2 / 3 / 2 / 6; text-align: center'>Escolha um local de nascimento</h1>
            <%= f.text_field :birth_place, :class => 'form-control align-self-center', :autocomplete =>'off', :required => 'true', :style => 'grid-area: 3 / 3 / 3 / 6'%>
            <a class='btn btn-primary align-self-center' id='fase-4' style='grid-area: 4 / 4 / 4 / 5'>Continuar</a>
        </div>
        <div class="form-group wrapper-newchar"  id='newchar-age'>
            <h1 style='grid-area: 2 / 3 / 2 / 6; text-align: center'>Qual a idade do seu personagem?</h1>
            <%= f.number_field :age, :class => 'form-control align-self-center', :autocomplete =>'off', :required => 'true', :style => 'grid-area: 3 / 3 / 3 / 6', :min => '18', :max => '89' %>
            <a class='btn btn-primary align-self-center' id='fase-5' style='grid-area: 4 / 4 / 4 / 5'>Continuar</a>
        </div>
        <div class="form-group wrapper-newchar"  id='newchar-mental'>
            <h1 style='grid-area: 2 / 3 / 2 / 6; text-align: center'>Seu personagem tem doenças mentais? (Opcional)</h1>
            <%= f.text_field :mental_illnesses, :class => 'form-control align-self-center', :autocomplete =>'off', :style => 'grid-area: 3 / 3 / 3 / 6'%>
            <a class='btn btn-primary align-self-center' id='fase-6' style='grid-area: 4 / 4 / 4 / 5'>Continuar</a>
        </div>
        <div class="form-group wrapper-newchar" id='newchar-sex'>
            <h1 style='grid-area: 2 / 3 / 2 / 6; text-align: center'>Escolha o sexo do seu personagem</h1>
            <%= f.text_field :sex, :class => 'form-control align-self-center', :autocomplete =>'off', :style => 'grid-area: 3 / 3 / 3 / 6', :required => 'true'%>
            <%= f.submit 'Enviar', :class => "btn btn-primary align-self-center", :id => 'submit', :style => 'grid-area: 4 / 4 / 4 / 5'%>
        </div>
    <% end %>
</div>

app/views/character/remove.html.erb
<h1>Character#remove</h1>
<p>Find me in app/views/character/remove.html.erb</p>

app/views/character/show.html.erb
<div class='topbar'>
    <p><%= @char.name %></p>
    <div class='topbar-vs'>
        <div>
            <p>Vida<p>
            <div class="progress">
                <div class="progress-bar bg-danger" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
        <div>
            <p>Sanidade<p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
    </div>
</div>