config/routes.rb
Rails.application.routes.draw do
  root 'user#login'
  
  get 'signup', to: 'user#new'
  post 'signup', to: 'user#create'

  get 'login', to: 'user#login'
  post 'login', to: 'user#login_attempt'
  
  get 'logout', to: 'user#logout'

  get 'player', to: 'player#home'
  get 'master', to: 'master#home'

  get 'newchar', to: 'character#new'
  post 'newchar', to: 'character#create'

  post 'rmchar', to: 'character#remove' 
  
  get 'character/:id', to: 'character#show', as: 'character'

  get 'setstat', to: 'stats#new'
  post 'setstat', to: 'stats#create'

  get 'skills', to: "skill#entrypoint"

  get 'agelimits', to: "stats#age_limits"
  post 'agelimits', to: "stats#new_points"
end

app/models/stat.rb
class Stat < ApplicationRecord
    belongs_to :character
    before_create :derive, :sum_less_than_461

    validates :str, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create
    validates :dex, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create
    validates :int, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create
    validates :app, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create
    validates :pow, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create
    validates :edu, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create
    validates :con, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create
    validates :siz, :presence => true,  numericality: { only_integer: true, less_than: 91, greater_than: 14 }, on: :create

    validates :str, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update
    validates :dex, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update
    validates :int, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update
    validates :app, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update
    validates :pow, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update
    validates :edu, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update
    validates :con, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update
    validates :siz, :presence => true,  numericality: { only_integer: true, less_than: 100, greater_than: 0 }, on: :update


    def improve_edu(i)
        for _ in 0..i-1
            val = rand(1..100)
            if val > self.edu
                d10 = rand(1..10)
                new_edu = d10 + edu.to_i
                if new_edu > 99
                    self.edu = 99
                else 
                    self.edu = new_edu
                end
            end
        end
    end

    
    private
    def gen_luck(advantage)
        t1 = rand(15..90)
        if advantage
            t2 = rand(15..90)
            self.luc = [t1, t2].max
        else
            self.luc = t1
        end
    end
    
    def sum_less_than_461
        if (str.to_i + dex.to_i + int.to_i + app.to_i + pow.to_i + edu.to_i + con.to_i + siz.to_i) > 460
            errors.add(:base, "Pontos maiores do que 460") 
        end
    end

    def derive
        self.lvl = 1
        self.done = false
        
        if self.character.age < 20
            gen_luck(true)
        else
            gen_luck(false)
        end

        gen_mov()
        gen_dx_body()
    end


    def gen_mov
        if str < siz and dex < siz 
            self.mov = 7
        elsif str > siz and dex > siz
            self.mov = 9
        else
            self.mov = 8
        end
    end

    def gen_dx_body
        mod = str.to_i + siz.to_i

        case mod
        when 2..64
            self.dx = '-2'
            self.body = '-2'
        when 65..84
            self.dx = '-1'
            self.body = '-1'
        when 85..124
            self.dx = '0'
            self.body = '0'
        when 125..164
            self.dx = '1d4'
            self.body = '1'
        when 165..204
            self.dx = '1d6'
            self.body = '2'
        when 205..284
            self.dx = '2d6'
            self.body = '3'
        else
            self.dx = '3d6'
            self.body = '4'
        end
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
    before_action :authenticate_user, :validate_char

    def new
        if not stats_set()
            @stats = Stat.new
        else
            redirect_to @char
        end
    end
    
    def age_limits
        if stats_done 
            redirect_to @char
        else
            @change = Stat.new()
            if stats_set() and not (@char.age >= 20 and @char.age <= 39) # => generate @stat            
                @status = set_limits
            else 
                @stat.update(:done => true)
                redirect_to @char
            end
        end
    end

    def new_points
        if stats_set() and not stats_done()
            @change = Stat.new()
            newstats_params()
            new_stat = 0
            old_stat = 0

            @status.symbols[:change].each do |s|
                old_stat += @stat[s]
                new_stat += params[:newpoints][s].to_i
            end

            must = @status.symbols[:must][0]

            if old_stat-new_stat == @status.points 
                improve_edu()

                if @stat.update(newstats_params.merge(must => @stat[must]-@status.points, :done => true)) 
                    redirect_to @char
                else 
                    render plain: @stat.errors.inspect
                end
            else 
                @change.errors[:base] << "The new points do not meet the criteria"
                render 'age_limits'
            end

        else 
            redirect_to @char
        end
    end

    def create
        if not stats_set()
            @stats = Stat.new(stat_params.merge(:character_id => @char.id))
            if @stats.save
                redirect_to :action => 'age_limits'
            end
        else
            redirect_to @char
        end
    end



    private
    def stat_params
        params.require(:stat).permit(:str, :dex, :app, :int, :pow, :edu, :siz, :con)
    end

    def newstats_params
        @status = set_limits
        params.require(:newpoints).permit(@status.symbols[:change])
    end

    def set_limits
        case @char.age
        when 18..19
            return AgeLimit.new(5, false)
        when 20..39
        when 40..49
            return AgeLimit.new(5, true)
        when 50..59
            return AgeLimit.new(10, true)
        when 60..69
            return AgeLimit.new(15, true)
        when 70..79
            return AgeLimit.new(20, true)
        when 80..89
            return AgeLimit.new(25, true)
        else
            raise ActionController::RoutingError.new('Invalid age') #should never run
        end
    end

    def improve_edu
        case @char.age
        when 18..19
        when 20..39
            @stat.improve_edu(1)
        when 40..49
            @stat.improve_edu(2)
        when 50..59
            @stat.improve_edu(3)
        when 60..69
            @stat.improve_edu(4)
        when 70..79
            @stat.improve_edu(4)
        when 80..89
            @stat.improve_edu(4)
        else
            raise ActionController::RoutingError.new('Invalid age') #should never run
        end
    end
end

class AgeLimit
    attr_reader :symbols, :details, :points, :colors
    def initialize(value, default)
        if default
            @symbols = { change: [:str, :con, :dex], must: [:app] }
            @points = value
            @details = { change: ['Força', 'Constituição', 'Destreza'], must: 'Aparência' }
            @colors = { change: ['bg-danger', 'bg-warning', 'bg-primary'], must: 'bg-info' }
        else
            @symbols = { change: [:str, :siz], must: [:edu] }
            @points = value
            @details = { change: ['Força', 'Tamanho'], must: 'Educação' }
            @colors = { change: ['bg-danger', 'bg-orange'], must: 'bg-pink' }
        end
    end
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/stats/age_limits.html.erb
<%= form_with scope: :newpoints, url: agelimits_path, local: true do |f| %>
    <div class='setstat-wrapper'>
        <h1 class='setstat-header'>Devido a idade <%= @char.name %> precisa reduzir</h1>
        <h2 class='setstat-points'><p><%= @status.points %></p> pontos de</h2>
        <div class='setstat-center-wrap'>
            <% @status.symbols[:change].each_with_index do |s,i| %>
                <div class='setstat-cwrap'>
                <%= f.label @status.details[:change][i], :class => "setstat-label #{@status.colors[:change][i]}", :style => "grid-area: 3 / #{3+i} / 3 / #{4+i};"%>
                <%= f.number_field s, :class => "card setstat-card #{@status.colors[:change][i]}", :min => '0', :max => @stat[@status.symbols[:change][i]],  :autocomplete =>'off', :required => 'true', :value => @stat[@status.symbols[:change][i]] %>
                </div>
            <% end %>
            <div class='setstat-cwrap' style="grid-area: 3 / 6 / 3 / 7" data-toggle="tooltip" data-placement="top" title='<%=@char.name%> também perderá <%=@status.points%> pontos de <%= @status.details[:must]%>'>
                <%= f.label @status.details[:must], :class => "setstat-label #{@status.colors[:must]}"%>
                <%= f.number_field @status.symbols[:must][0], :class => "card setstat-card #{@status.colors[:must]}", :autocomplete =>'off', :disabled => 'true', :value => @stat[@status.symbols[:must][0]] - @status.points, :required => 'true'%>
            </div>
        </div>

        <%= f.submit 'Enviar', :class => "btn btn-primary align-self-center", :style => 'grid-area: 5 / 4 / 5 / 6'%>
        <% if @change.errors.any? %>
            <div class="toast errors-toast" style="grid-area: 1/7/2/9; " role="alert" aria-live="assertive" data-autohide="false" aria-atomic="true">
                <div class="toast-header">
                    <strong class="mr-auto">Erros</strong>
                    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body">
                    <% for message_error in @change.errors.full_messages %>
                    <p><%= message_error %></p>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/stats/new.html.erb
<%= form_with scope: :stat, url: setstat_path, local: true do |f|%>
    <div class='setstat-wrapper'>
        <h1 class="setstat-header align-self-center" >Defina os atributos de <%=@char.name%></h1>
        <h2 class="setstat-points">
            <p id="points">460</p> pontos restantes
        </h2>
        <div class='setstat-cwrap' style="grid-area: 3 / 3 / 3 / 4" >
            <%= f.label 'Força', :class => "setstat-label bg-danger"%>
            <%= f.number_field :str, :class => 'card setstat-card bg-danger', :min => '15', :max => '90',  :autocomplete =>'off', :required => 'true', :'data-index' => '0'%>
        </div>
        <div class='setstat-cwrap' style="grid-area: 3 / 4 / 3 / 5" >
            <%= f.label 'Destreza', :class => "setstat-label bg-primary"%>
            <%= f.number_field :dex, :class => 'card setstat-card bg-primary', :min => '15', :max => '90', :autocomplete =>'off', :required => 'true', :'data-index' => '1'%>
        </div>
        <div class='setstat-cwrap' style="grid-area:3 / 5 / 3 / 6" >
            <%= f.label 'Inteligência', :class => "setstat-label bg-success"%>
            <%= f.number_field :int, :class => 'card setstat-card bg-success', :min => '15', :max => '90', :autocomplete =>'off', :required => 'true', :'data-index' => '2'%>
        </div>
        <div class='setstat-cwrap' style="grid-area: 3 / 6 / 3 / 7" >
            <%= f.label 'Constituição', :class => "setstat-label bg-warning"%>
            <%= f.number_field :con, :class => 'card setstat-card bg-warning', :min => '15', :max => '90', :autocomplete =>'off', :required => 'true', :'data-index' => '3'%>
        </div>
        <div class='setstat-cwrap' style="grid-area: 4 / 3 / 4 / 4" >
            <%= f.label 'Aparência', :class => "setstat-label bg-info"%>
            <%= f.number_field :app, :class => 'card setstat-card bg-info', :min => '15', :max => '90', :autocomplete =>'off', :required => 'true', :'data-index' => '4'%>
        </div>
        <div class='setstat-cwrap' style="grid-area: 4 / 4 / 4 / 5" >
            <%= f.label 'Poder', :class => "setstat-label bg-secondary"%>
            <%= f.number_field :pow, :class => 'card setstat-card bg-secondary', :min => '15', :max => '90', :autocomplete =>'off', :required => 'true', :'data-index' => '5'%>
        </div>
        <div class='setstat-cwrap' style="grid-area: 4 / 5 / 4 / 6" >
            <%= f.label 'Tamanho', :class => "setstat-label bg-orange"%>
            <%= f.number_field :siz, :class => 'card setstat-card bg-orange', :min => '15', :max => '90', :autocomplete =>'off', :required => 'true', :'data-index' => '6'%>
        </div>
        <div class='setstat-cwrap' style="grid-area: 4 / 6 / 4 / 7" >
            <%= f.label 'Educação', :class => "setstat-label bg-pink"%>
            <%= f.number_field :edu, :class => 'card setstat-card bg-pink', :min => '15', :max => '90', :autocomplete =>'off', :required => 'true', :'data-index' => '7'%>
        </div>
        <%= f.submit 'Continuar', :class => "btn btn-primary align-self-center", :id => 'submit', :style => 'grid-area: 5 / 4 / 5 / 6'%>
    </div>
    <%end%> 